# Development only!

version: '3'

volumes:
  pg_data:

networks:
  dodo:

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - dodo

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dodo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: "bin/dev" # TODO: Split assets/server
    tty: true
    volumes:
      - .:/rails
      # TODO: Add bundler volume
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgres://postgres:secret@postgres:5432
    depends_on:
      - db
      - redis
    networks:
      - dodo
