default: &default
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL", "redis://localhost:6379/1") %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
  channel_prefix: dodo_production
